# Generated by Django 4.2.4 on 2023-09-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
