# Generated by Django 4.2.4 on 2023-09-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuarios', '0003_alter_usuario_idade_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.TextField(max_length=255),
        ),
    ]
